version: "3.9"

services:
  app:
    build:
      context: . # Location of your Dockerfile
      dockerfile: Dockerfile
    container_name: express_app
    ports:
      - "3000:3000" # host:container
    environment:
      - NODE_ENV=production
      # - PORT=3000       # optional if your app reads from process.env.PORT
    restart: unless-stopped
    volumes:
      - .:/app # optional: mount code for live reload (remove in production)
    networks:
      - app-network
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP Thrift (for OTEL HTTP exporter)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    restart: always
networks:
  app-network:
    driver: bridge
